### ISSUE TITLE
Cleanup accounts catalog & authorised sites

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#1040]
**Describe the bug**
In case an account disappears from the keyring (ex: ), the authorised sites & account catalog don't self-heal.

**To Reproduce**
- delete an account from storage using Storage Area Explorer extension
- restart extension

=> trusted sites data still includes references to the deleted account
=> popup home displays "Unknown account"
=> dashboard account dropdown displays "Unknown account"

For engineering:
Cooldown work : cleanup of both account catalog and authorised sites on extension startup, based on accounts present in the keyring

**Comment by chidg** [comment]
Closing as low priority
