### ISSUE TITLE
Support EVM L2

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#1067]

**Comment by 0byt** [comment]
Target chains:
* Base / Optimism, etc (OP Stack)
* Arbitrum / Arbitrum Nova
* Polygon (?)
* Avail (?)
* Research other possible chains that we need to support

Current State:
* It works these days because we take some margin on our computation (Gas limit with 2% margin)
* For Optimism, currently base fee doesn't work 
* Currently ignoring cost of transaction of L1

Output:
- [ ] UI: Need to show L1/L2 fee, show total to user
- [ ] Wallet: Compute cost of L1 fee
- [ ] Review Send Max feature to take these fees into account
- [ ] Setup infra to be able to scale to other chains later

**Comment by 0xKheops** [comment]
Implemented in #1146
