### ISSUE TITLE
Extended EVM Chains / Assets List

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#1069]

**Comment by 0byt** [comment]
Will be part of Chaindata, so need to sync with Alec

Current State:
* Half of the info is ethereum-list, 1 file per known network
* Fetch network logos from here, this currently doesn't have token logos

Goal:
* Merge data sources: token/network info from coingecko + ethereum list
* Query coingecko for native tokens
* Then add the most used networks to this
* Override some commonly used logos

**Comment by chidg** [comment]
Closed by #1126
