### ISSUE TITLE
Ledger Substrate issues

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#1161]
Many users are confused by the limitations of Ledger on substrate, and don't understand why they can't access funds which they have sent to an address on a chain which is not supported by a Ledger app, or else corresponds to an address derived by a Ledger app for a different chain.

In order to reduce this confusion, we should do the following:
- write a blog post about how Ledger works on Substrate, what the limitations are, and what the choices are for users
- Include a UI element in the Connect Ledger account screen for Polkadot Ledger accounts linking to this blog post
- On the signing approval screen in the popup, when decoding the transaction, if the recipient address is one of the accounts in Talisman, detect if that account is a Ledger account and if the transaction is on a non-supported chain. If so, show a warning.
- If pasting an address in the send funds UI, detect if the address corresponds to an existing Ledger account on another chain and show a warning

**Comment by 0xKheops** [comment]
might want to display a warning when copying the address of a ledger account

**Comment by chidg** [comment]
Closing as complete/no longer relevant due to generic Ledger app
