### ISSUE TITLE
Polkadot Vault QR performance

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#1198]
performance problems for big payloads.

Easy to reproduce with a 5000 characters message signing

**Comment by 0xKheops** [comment]
can't reproduce, worked fine even with 100K characters here

can anyone else try ? @alecdwm maybe ?

**Comment by alecdwm** [comment]
@0xKheops nope, works just fine for me! Did we have a user with this issue or something?

**Comment by 0xKheops** [comment]
Let's wait for #1210 to be released and ask the user to test again

**Comment by chidg** [comment]
@0xKheops can we follow up on this?

**Comment by chidg** [comment]
Closing as stale
