### ISSUE TITLE
Update coingecko prices for various tokens

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#1200]
**Describe the bug**
Certain newer tokens in chaindata have price on coingecko, but we do not show it
Can we scan these tokens and update chaindata

**Screenshots**
If applicable, add screenshots/recordings to help explain your problem.

<img width="1141" alt="image" src="https://github.com/TalismanSociety/talisman/assets/119995565/5c5b5621-8970-4ba6-9a0e-14fd4b06ec58">

**Comment by chidg** [comment]
@alecdwm can this be closed?

**Comment by alecdwm** [comment]
Not yet

**Comment by chidg** [comment]
@alecdwm how about now? 😂

**Comment by alecdwm** [comment]
Not yet! 😆 

We have the updated coingecko ids but still need to put them into chaindata

https://docs.google.com/spreadsheets/d/1jJk64RlfaUsikVmmD6xzuw0G3I6XZpQlzKWQF5utNPQ/edit#gid=442576719

**Comment by alecdwm** [comment]
Closed by [a177a1318a](https://github.com/TalismanSociety/chaindata/commit/a177a1318a6b019533e48d0c4407af43e681657f)
