### ISSUE TITLE
钱包转入代币，也显示到账和记录，可是账户余额就是没有。

### ISSUE THREAD

**Issue by yeshili** [TalismanSociety/talisman#1201]
![image](https://github.com/TalismanSociety/talisman/assets/24773628/08a7e0c6-9d4c-470d-9178-143c281b03fa)
![image](https://github.com/TalismanSociety/talisman/assets/24773628/5ad8eecc-d253-455d-81ed-6ea1ae47fe81)

转账区块链记录
https://polkadot.subscan.io/extrinsic/18690527-2

麻烦查看一下，谢谢！

**Comment by yeshili** [comment]
![image](https://github.com/TalismanSociety/talisman/assets/24773628/373b391d-901e-48fc-949c-26a387e3a890)
都几个小时这样子，到账如果是延迟，是一个很大的问题啊

**Comment by yeshili** [comment]
148xjvaNAbrDChppSUKfbkERaNgmvJSbar7L832dapKs6Yxw
接收钱包地址，未到账，但是有记录！

**Comment by yeshili** [comment]
![image](https://github.com/TalismanSociety/talisman/assets/24773628/06c58ba5-d897-4172-829a-b646dad88688)

Transfer block 3 hours ago, the record, but the balance can not account, please see, thank you, what happened!


aaddress：148xjvaNAbrDChppSUKfbkERaNgmvJSbar7L832dapKs6Yxw

**Comment by 0byt** [comment]
您好，上周DOT网络因为交易量太大受到很大的影响，交易和账号余额都有延迟问题
请问您是从交易所移动 DOT 到钱包的吗？DOT是否还留在交易所上呢？
另外，如果还有其他急迫问题的话，我们在 discord.gg/talisman 上有24/7 的技术支援，可直接在 Discord 上发信息给我们

**Comment by chidg** [comment]
Closing, for user support please join our Discord.
