### ISSUE TITLE
New balances - Write migration to ensure that tokens with non-zero balances are still enabled post-upgrade

### ISSUE THREAD

**Issue by alecdwm** [TalismanSociety/talisman#1218]
The new balances upgrade includes a enabled/disabled flag for tokens.

We should make sure that users with non-zero balances for a token in the previous version of the wallet will continue to see those balances in the new version.

Also we should check to make sure that the balances cache for those tokens is not deleted during the upgrade.

**Comment by chidg** [comment]
Should not be an issue, will be tested during pre-release regression tests
