### ISSUE TITLE
Investigate/fix DatabaseClosedError

### ISSUE THREAD

**Issue by alecdwm** [TalismanSociety/talisman#129]
https://sentry.io/organizations/talisman/issues/3430153249/?project=6163349&query=is%3Aunresolved+indexeddb&statsPeriod=14d
https://sentry.io/organizations/talisman/issues/3430153237/?project=6163349&query=is%3Aunresolved+indexeddb&statsPeriod=14d
https://sentry.io/organizations/talisman/issues/3370865107/?project=6163349&query=is%3Aunresolved+indexeddb&statsPeriod=14d
https://sentry.io/organizations/talisman/issues/3430153236/?project=6163349&query=is%3Aunresolved+indexeddb&statsPeriod=14d
...etc

Potential causes:
- [DB Upgrades](https://www.nerd.vision/post/how-we-solved-a-case-where-indexeddb-did-not-connect)

**Comment by chidg** [comment]
Fixed (mostly) by dedexification
