### ISSUE TITLE
Bridge Hub Integration: View bridged assets from in Asset Hub in Wallet

### ISSUE THREAD

**Issue by alistair-singh** [TalismanSociety/talisman#1308]
Fearture request: A user should be able to see any bridged assets that they own in their wallet.

Asset Hub now supports foreign assets bridged through Bridge Hub. These assets are stored in a different instance of the assets pallet called [ForeignAssets](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs#L378-L412) from version 1.7 release of Asset Hub.

There are two bridges currently deployed in Rococo
1. Snowbridge (bridges to Sepolia Ethereum testnet)
3. Westend Bridge (bridges to Westend substrate based testnet)

For Snowbridge the token that is Bridged is WETH (Wrapped Ether). Please see [docs](https://docs.snowbridge.network/rococo-testnet/rococo-sepolia-token-transfers) for more information on how to interact with the bridge and query asset balances.

We have plans for launch in Kusama and Polkadot (bridging to Ethereum mainnet) by the end of March. 

- Snowbridge Team

**Comment by chidg** [comment]
Thanks for bringing this to our attention @alistair-singh. I'll raise it with our product team and we will prioritise; in the meantime, you are welcome to submit a PR to our balances modules to help us support the `ForeignAssets` pallet.

cc asset support superstar @alecdwm

**Comment by musnit** [comment]
@chidg @alecdwm FYI SubWallet has added support for foreign assets here: https://github.com/Koniverse/SubWallet-Extension/commit/3218c6f2880c9f037116873e9699a124fda84dde - hopefully code is useful as a reference

**Comment by musnit** [comment]
@chidg bump on this. we are now live on polkadot mainnet (https://app.snowbridge.network/) and users can't see their assets in their wallet due to lack of foreign asset support.

**Comment by alistair-singh** [comment]
@chidg bump on this. There are now a few assets stored in the foreign assets pallet on mainnet Asset Hub.

Subscan has added support as well:
https://assethub-polkadot.subscan.io/foreign_assets

Assets bridged by Snowbridge:
WETH
WBTC
USDC
USDT

Assets bridged by Polkadot-Kusama bridge:
KSM

Non bridged assets:
MYTH
HDX
GLMR

For bridged assets that conflict with other assets such as USDC and USDT, you can use `USDC.e` or `USDC-Snowbridge` to differentiate them.

**Comment by nicolares** [comment]
Hey all! Thanks for adding support for WETH from snowbridge.

In addition that (I already flagged this with @jonathanpdunne but bumping here in case it helps) [Turtle](https://app.turtle.cool/) is already live but users are not seeing their USDC.e and USDT.e balances. Currently only Subscan supports all of them and not in the "neatest" way so hopefully you guys can help out by adding all available foreign assets too 🙏

**Comment by alecdwm** [comment]
Hey @nicolares!

We didn't realise there would be foreign assets which could be queried via `ForeignAssets.Asset` and not `ForeignAssets.Metadata`.

[We've added the missing ones](https://github.com/TalismanSociety/chaindata/commit/1255432bb0641b10312d0ec77108d8b20f1f1ad2#diff-fcee67c8e2690a3d457a621a587b7873c105e7b1ecab9ae78acee8d1e64a8161R3867), including the aforementioned WETH, WBTC, USDC, USDT, KSM, MYTH, HDX, GLMR as well as PEPE, TBTC, WSTETH, TONCOIN, DAI and SHIB.

**Comment by chidg** [comment]
Closed as complete
For future assets when no metadata present, they'll need to be added manually - please contact us if so
