### ISSUE TITLE
Change password - close browser behavior

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#1337]
Either :
- Inform the user that they shouldn't be closing the browser while password is being changed
- Handle the scenario where browser is being closed while password is being changed

At this time, it seems like in this case individual keyring accounts passwords are changed, but not all

Note : risk of related problems is quite high with a high number of accounts, as it feels like wallet is frozen

**Comment by chidg** [comment]
Closed by #1354
