### ISSUE TITLE
TUR staking changes

### ISSUE THREAD

**Issue by itsbirdo** [TalismanSociety/talisman#136]
There is an upcoming upgrade to the Turing staking pallet will change how your staked tokens are stored on the chain. Before, staked tokens were “reserved”. They were completely frozen and couldn’t be used for any other purpose. Instead of staked tokens being reserved, after the upgrade they will be “locked”. Locked tokens are way more flexible than their reserved counterparts. For example, tokens that are locked for staking can still be used to vote for governance proposals!

Want to read more about locked vs reserved tokens? https://wiki.polkadot.network/docs/build-protocol-info#free-vs-reserved-vs-locked-vs-vesting-balance

Call to Action
Please make sure your UI reflects this change from reserved to locked. If you do not do so, it may cause confusion to the consumer. We will send you another message once it's live in Turing next week.

Timeline Targets
Turing Staging: Thursday, Aug 4, 2022
Turing: Tuesday, Aug 9, 2022

**Comment by chidg** [comment]
Fixed at some point!
