### ISSUE TITLE
Creating a new account/mnemonic asks me to backup my seed twice

### ISSUE THREAD

**Issue by prury** [TalismanSociety/talisman#1382]
**Describe the bug**
When i create a new account, i normally go trough the process, write down my seed and insert it again on the step that verifies that i had wrote it down properly. Even if i go trough this process, i receive a warning that i have to backup my wallet once more: 
![image](https://github.com/TalismanSociety/talisman/assets/36627808/f484930c-f29f-48c5-8789-7ba006ce4650)

**To Reproduce**
Steps to reproduce the behaviour:

Create new Polkadot account with new mnemonic -> go trough mnemonic backup process -> check warning

**Expected behaviour**
warning should not appear

**Environment (please complete the following information):**

- OS: Windows 10
- Browser: Firefox

For engineering:
**Test**
Should a test be written to accompany the bug fix that squashes this bug? If not, what is the reasoning for not including a test case?

**Comment by chidg** [comment]
Thanks for the report @prury
