### ISSUE TITLE
Wrong transferable balance

### ISSUE THREAD

**Issue by Juanma0x** [TalismanSociety/talisman#1388]
The way transferable balance might not be updated to the current `balance` pallet.
Example:
Account 15aVbh9j99DyEJo9pYDs6UMB25ybHAteb4xmjnXkiBx855Qo shows a transferable balance of 0 in Talisman:
![image](https://github.com/TalismanSociety/talisman/assets/120041850/5a6a22d8-6758-4f34-8dee-104cd6a6f4af)

While a free balance of 8.47 DOT (at the time of writing) querying the chain state (`system.account`):
![image](https://github.com/TalismanSociety/talisman/assets/120041850/212963f8-76ad-457b-a0fb-ba3e26a8303d)

Related:
https://github.com/polkadot-js/apps/issues/9988
https://github.com/paritytech/polkadot-sdk/issues/1833#issuecomment-1805764506

**Comment by chidg** [comment]
Thanks @Juanma0x , we are aware of this and working on it.
