### ISSUE TITLE
Copy address fails

### ISSUE THREAD

**Issue by wirednkod** [TalismanSociety/talisman#1427]
**Describe the bug**
When trying to copy the address in any of the ways the "Oops Sorry, an error occured in Talisman." screen appears

**To Reproduce**
Steps to reproduce the behaviour:

1. Unlock your wallet
2. Go to the account
3. try to copy the address either from the tile screen:
![image](https://github.com/TalismanSociety/talisman/assets/5408605/f2fde12b-9342-429d-9bc3-55d57533bf26)
or from the second screen:
![image](https://github.com/TalismanSociety/talisman/assets/5408605/e47d7039-1661-444b-a99e-171ed05d09b1)

Copy works fine  when trying to copy from network copy screen:
![image](https://github.com/TalismanSociety/talisman/assets/5408605/12c7912d-149c-4bb3-adc8-fae782614aa5)

 
**Expected behaviour**
Address should be copied to the clipboard and a success message should appeear

**Environment (please complete the following information):**

- OS: MacOS Sonoma
- Browser Chrome
- Version 124.0.6367.119 (Official Build) (arm64)

**Comment by chidg** [comment]
Thanks for the report @wirednkod , should be able to get a temporary OTA fix out for this quickly.

**Comment by chidg** [comment]
Should be good now @wirednkod as we have removed the offending data from our chains config.

**Comment by wirednkod** [comment]
Works like a charm (pun intended). Thank you @chidg
