### ISSUE TITLE
Unable to connect to Aave

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#1429]
**Describe the bug**
When using the 'Browser Wallet' option to connect to https://app.aave.com/, the wallet does not connect, and shows the below error message
<img width="427" alt="Screenshot 2024-05-08 at 10 42 39 AM" src="https://github.com/TalismanSociety/talisman/assets/3326734/7efc9212-3878-4aa2-96d5-62614a17d926">

Connecting with Metamask works as expected.

**To Reproduce**
Attempt to connect to https://app.aave.com/ using Talisman

**Comment by 0xKheops** [comment]
Looks like they're expecting a isUnlocked() function on the injected provider :/

**Comment by chidg** [comment]
Closed by #1433
