### ISSUE TITLE
Bifrost test network failed to integrate ledger

### ISSUE THREAD

**Issue by yooml** [TalismanSociety/talisman#1517]
We used zombienet to build a test chain integrated with metadataHash, and found that signing errors would occur when signing with talisman, but not when using polkadot.js and subwallet.

You can try signing here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost-polkadot-rpc.devnet.liebi.com%2Fws#/accounts

**Comment by yooml** [comment]
You can verify the availability of metadataHash:
```
git clone https://github.com/yooml/signer-test
cd signer-test
yarn && yarn start:dev
```

**Comment by chidg** [comment]
Hi @yooml , please let us know if this can now be closed as I believe it was fixed with https://github.com/TalismanSociety/talisman/commit/c7c1221d802c7504fa12055b4c8878fe5b0abf3e

**Comment by yooml** [comment]
@chidg Yes, it's been fixed.
