### ISSUE TITLE
Polkadot Vault metadata issues

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#1525]
Multiple users have reported issues when attempting to update metadata for a network with Polkadot vault. 
See tickets 1400 and 1405 in Talisman community Discord.

**Comment by alecdwm** [comment]
Tagging https://github.com/novasamatech/parity-signer/issues/2073

**Comment by alecdwm** [comment]
<img src="https://github.com/TalismanSociety/talisman/assets/2741569/d3317df1-44d6-4065-91de-9fc83f0346d2" width="300" />
