### ISSUE TITLE
Feature Request - Add custom Ledger account import

### ISSUE THREAD

**Issue by filippoweb3** [TalismanSociety/talisman#1527]
It would be helpful to have the option to select `account type` and `address index` when importing a Ledger account, as allowed by Polkadot-JS UI (currently not working with the new Ledger apps)

![Screenshot 2024-07-03 at 09 47 28](https://github.com/TalismanSociety/talisman/assets/110459737/3e330343-971f-4523-8f4a-e1a491a2c615)

I have a Ledger account with second derivation (i.e. `address index` != 0) and I believe addresses that are currently available on Talisamn are only using first derivation (similarly to Ledger Live and Subwallet).

**Comment by chidg** [comment]
Hi @filippoweb3 , this is now complete and out in Talisman v1.29.3
Closed by https://github.com/TalismanSociety/talisman/pull/1516 and https://github.com/TalismanSociety/talisman/pull/1523
