### ISSUE TITLE
Polkadot Vault no longer working

### ISSUE THREAD

**Issue by eskimor** [TalismanSociety/talisman#1533]
In particular Talisman now just fails to scan the QR code of the signer. I can hold it there forever, change display brightness, go closer, farther. Nothing works. This used to work completely flawlessly.

**Comment by chidg** [comment]
Hi @eskimor , we are aware of an issue with reading QR codes on Firefox and have a fix in progress.

In general we need much more information that you've provided for a bug report - *at least* which browser, and Talisman version. 
Please let us know if you're not on FF.

**Comment by eskimor** [comment]
Thanks! Indeed I am on Firefox, version latest, sorry will be more descriptive next time. :-) And thanks for fixing!
