### ISSUE TITLE
send funds: no error message if EVM account is empty (no native tokens) and trying to transfer ERC20s

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#1544]
<img src="https://github.com/user-attachments/assets/4bf6949b-4153-42dd-b9bc-7212799f7145" width="33%" />

**Comment by alecdwm** [comment]
Substrate example:

<img src="https://github.com/user-attachments/assets/bab5c276-ae44-41e6-a20a-dca6a02de019" width="33%" />
<img src="https://github.com/user-attachments/assets/310c7e93-f4ae-4810-b0de-6da53331957e" width="33%" />

With holdings:

<img src="https://github.com/user-attachments/assets/bdcef9d9-09d2-4e4d-b817-3ac1125802a9" width="49%" />
<img src="https://github.com/user-attachments/assets/c483ae15-4426-4db1-b5bc-4f4f1bdff3d0" width="49%" />

**Comment by chidg** [comment]
Closing as complete
