### ISSUE TITLE
On-boarding with watched account doesn't look for ENS addresses

### ISSUE THREAD

**Issue by prury** [TalismanSociety/talisman#1550]
**Describe the bug**
Extension won't check for ENS address validity when on-boarding using a watched account

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Onboarding proccess with a fresh extension install
2. Choose to start with a watched account
3. type any ENS address
4. See `invalid address` error

**Screenshots**
![image](https://github.com/user-attachments/assets/e03626d4-4ace-4db4-a570-56090f267906)

**Environment (please complete the following information):**

- OS: Ubuntu 24.04
- Browser: Chrome
- Version: 126.0.6478.182

**Comment by 0xKheops** [comment]
Thank you for reporting this!
