### ISSUE TITLE
Please Remove astar-gas-station.herokuapp.com as it will be deleted

### ISSUE THREAD

**Issue by niklabh** [TalismanSociety/talisman#1601]
**Describe the bug**

Please Remove astar-gas-station.herokuapp.com as it will be deleted

https://github.com/TalismanSociety/talisman/blob/16b6b349cf5c23467a61d8aca366db5735ada04d/apps/extension/src/ui/hooks/useTip.ts#L26

Please use official astar api

**Comment by chidg** [comment]
Closed by #1615
