### ISSUE TITLE
update network button only gets active when focusing subscan input

### ISSUE THREAD

**Issue by prury** [TalismanSociety/talisman#1604]
**Describe the bug**
When editing a existing network that hasn't a predefined subscan address set, one must focus on the subscan field in order to make the `update network` button active

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to settings -> Network & Tokens -> Manage Networks -> choose a network that doesn't have a subscan address(eg. Ajuna on Polkadot)
2. Edit fields/Mark checkboxes
3. Check update network button state

**Expected behaviour**
update network button should be active if you edit the form

**Screenshots**

[Gravação de tela de 2024-09-09 21-14-57.webm](https://github.com/user-attachments/assets/363036d4-3fb4-43ac-8777-d38d8b92c170)

**Environment (please complete the following information):**

- OS: Ubuntu 24.04
- Firefox

**Comment by camfairchild** [comment]
This appears to be only necessary if the subscan field is empty. See for example Acala.

**Comment by 0xKheops** [comment]
Thank you for the report!
