### ISSUE TITLE
Send funds: Polkadot Ledger Generic app restriction

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#1611]
Prevent sending funds to ledger generic accounts on chains that dont have the CheckMetadataHash signed extension

For example: 
Avail network is not supported on the generic Ledger app. When sending funds on Avail, a Polkadot generic Ledger app account should not appear in the list of recipients.

**Comment by chidg** [comment]
I think this can be closed, right @0xKheops ?

**Comment by 0xKheops** [comment]
yes
