### ISSUE TITLE
Mozilla extension not available

### ISSUE THREAD

**Issue by nikunjkumarnakum** [TalismanSociety/talisman#1639]
![Screenshot 2024-10-08 110204](https://github.com/user-attachments/assets/65bc1756-1840-43e3-b8bf-9c28ed030a15)

**Comment by chidg** [comment]
Hi @nikunjkumarnakum , yes we are aware of the issue! Apologies for this. We are still in progress with the Firefox add on store review process. Unfortunately it has been quite a drawn out process. We are slowly making progress though and we hope to have the wallet available again on Firefox soon.

**Comment by chidg** [comment]
Please to announce Talisman is now available again on the Firefox Add on store. Thanks for your patience! 
Closing this.

**Comment by nikunjkumarnakum** [comment]
Thank you for making your extension available on Firefox. I appreciate the effort you put into this and am glad to have access to it.
