### ISSUE TITLE
[Transfer from Web Repo] Does Talisman use https://polkadot.js.org/phishing/# to block the addresses involved in the scam?

### ISSUE THREAD

**Issue by ccris02** [TalismanSociety/talisman#551]
Based on the polkadot{.js}/phishing addresses are only blocked by [polkadot{.js} apps](https://polkadot.js.org/apps) and [Fearless Wallet](https://fearlesswallet.io/).
"The addresses are blocked in wallets such as polkadot{.js} apps and Fearless Wallet."
Would we be able to integrate address blocking in Talisman?

**Comment by jonathunne** [comment]
Talisman does block sites listed in the polakdot{.js} phishing list 👍
