### ISSUE TITLE
[Transfer from Web Repo] Add hardware wallet and import polkadot js wallet options to getting started page

### ISSUE THREAD

**Issue by hitchhooker** [TalismanSociety/talisman#554]
I am looking to change from polkadot js wallet to talisman, but it seems there is no option to import existing wallet other than with privatekeys/mnemonics which im not very keen to do as an owner of very many wallets addresses. 
I such feature perhaps existing or coming in the future where you could add polkadot-js wallet to talisman?

**Comment by chidg** [comment]
Fixed - these options available in onboarding for some time
