### ISSUE TITLE
Store Polkadot Vault logo id in chain data

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#701]
Parity Signer/Vault uses nova-specific ids for chain logo ids. Most of the time they match the spec name but it's not always the case.

We'd need an additional property for chains in chaindata, to indicate the logo id for each chain.

See this issue : https://github.com/paritytech/parity-signer/issues/1782#issuecomment-1509745189

**Comment by chidg** [comment]
Closing as stale
