### ISSUE TITLE
Encrypt/Decrypt changes

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#731]
- modify api methods return values
- simplify popup UI

Currently both encryptMessage and decryptMessage return a value with this shape : 

```json
{
    "id":null,
    "result":"0xabcdef......"
}
```
id is always null and should be removed.
also on the decryptMessage method, we could return the hex-decoded string value, instead of the current hex encoded value. => need to wait for Sumi's aknowledgement before proceeding as this would be a breaking change.

On the UI side, since the objective is not only to encrypt/decrypt small messages, but also files, it seems necessary to not show the message that are to be encrypted/decrypted
Tho, if the message is less than 100 (TBD) characters, we could assume it's human readable and show it the user.

**Comment by chidg** [comment]
Closing as stale
