### ISSUE TITLE
EVM json export isn't compatible with Metamask

### ISSUE THREAD

**Issue by jonathanpdunne** [TalismanSociety/talisman#737]
Just attempted to export an EVM account from Talisman and import into Metamask. When I attempted to import the account into Metamask, I was presented with an error explaining that the JSON file was "not a v3 wallet":

![image](https://user-images.githubusercontent.com/37194960/236381449-61b46d6a-01fe-427d-8b18-d9083bd09b8a.png)

**Comment by chidg** [comment]
Close as stale/low priority
