### ISSUE TITLE
Add `Astar` as a default token option for the wallet empty state

### ISSUE THREAD

**Issue by helloitsbirdo** [TalismanSociety/talisman#79]
Given I have installed the Talisman wallet but not imported or added any account
When I see the empty state of Talisman, it currently includes `GLMR` and `MOVR` but doesn't include `ASTAR`
Let's add it :)

![image](https://user-images.githubusercontent.com/93915849/177921171-46c419b8-b8d2-430c-8f91-83be96fb772d.png)

**Comment by 0xKheops** [comment]
tricky one as it's both substrate and evm, could cause confusion
