### ISSUE TITLE
Tokens not appearing

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#804]
Strange behavior identified this morning
- My hydradx assets were appearing in talisman (HDX, DOT, ZTG, WETH)
- Swapped WETH to USDT on hydradx
- USDT didn't appear in talisman, browser restart didn't help
- at some point i noticed that only HDX (native token) was appearing for hydradx chain, the other ones (substrate-tokens type) did not
- turning on testnets made them reappear
- turning off testnets didn't make them disappear (they shouldn't, but was trying to identify if there was a wrong isTestnet flag somewhere)

**Comment by alecdwm** [comment]
Some more information from my side:
While we were investigating the missing assets, I realised that my wallet was also missing a number of assets.

I added Kheops's account into my wallet as a watched account.

Also, I was working on i18n, so please ignore the errant emojis.

| Here's what I could see: | Versus what Kheops could see: |
| --- | --- |
| ![](https://cdn.discordapp.com/attachments/940179502384939079/1111111564376932394/Screenshot_2023-05-25_at_12.00.35.png) | ![](https://cdn.discordapp.com/attachments/940179502384939079/1111111870095577159/image.png) |

Notice the lack of ASTAR on my view. You can't tell in the screenshot, but I also couldn't see AMPE.  
On the other hand, Kheops couldn't see ZTG (as well as the subject of this issue: USDT on HydraDX).

In my case, turning **off** testnets restored all of the missing assets.

![](https://media3.giphy.com/media/ukGm72ZLZvYfS/giphy.gif?cid=ecf05e47xlfzqvqs3xwgneop042018zh5r4tx55kxbv0c627&ep=v1_gifs_related&rid=giphy.gif&ct=g)

**Comment by alecdwm** [comment]
Duplicated by https://github.com/TalismanSociety/talisman/issues/999

**Comment by 0xKheops** [comment]
@alecdwm should we close this and #999 ?
haven't experienced this for months

**Comment by alecdwm** [comment]
Yeah we can create a new issue if it happens again
