### ISSUE TITLE
De-integrate Banxa

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#816]
Banxa is no longer able to renew the integration agreement we have with them. We can still link out to Banxa and users can manually fill in their account details, but at some point the `talisman.banxa.com` url will stop working.

Currently the url parameters passed by our modal still work on the general `checkout.banxa.com` page. We should test this again to confirm but if still working then just update the url but maintain the modal.

Currently not urgent but may become so when our integration agreement expires if they deactivate the subdomain.

**Comment by 0xKheops** [comment]
fixed in #1099
