### ISSUE TITLE
Interlay Asset Support

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#909]
@0byt to supply more details

**Comment by alecdwm** [comment]
## List of Tokens to be supported
### On Interlay
LP tokens
- [x] LP iBTC/DOT
- [x] LP iBTC/USDT
- [x] LP DOT/INTR

qTokens
- [x] qIBTC
- [x] qUSDT
- [x] qDOT

### On Kintsugi
LP tokens 
- [x] LP kBTC/USDT
- [x] LP kBTC/KSM
- [x] LP KSM/KINT

qTokens
- [x] qUSDT
- [x] qkBTC
- [x] qKSM

**Comment by alecdwm** [comment]
- [x] Add new token logos
