### ISSUE TITLE
MM Ethereum window override issues

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#915]
https://www.notion.so/talismanwallet/Fix-MM-Talisman-conflicts-becce52afa444410a156a466b7283cb8

**Comment by 0byt** [comment]
Pedro is still facing this issue now, this is the video of the issue. 
"when I first login to a website, talisman takes over the window.ethereum, so when I choose to connect with metamask, talisman pops up then I have to refresh the screen to make it work"

https://github.com/TalismanSociety/talisman/assets/119995565/5177501a-bceb-4f83-b7c1-1c960162487e

**Comment by 0byt** [comment]
Roy from Astar team also reported issues today
"Hi team, 
I would like to report something strange. I found that sometimes the data of “window.ethereum”(MetaMask) is overwritten by “window.talismanEth”. Were you aware of this issue? It causes an issue when users select 'MetaMask' but the app connects to Talisman instead. It would be great if it is resolved in a future update of the Talisman extension."


![Image](https://github.com/TalismanSociety/talisman/assets/119995565/9b650bdb-1c4c-4a30-831d-cfc8171d0418)

**Comment by chidg** [comment]
Raised a support request in the Phantom Devs Discord


![Image](https://github.com/TalismanSociety/talisman/assets/3326734/b73fae16-927f-46ae-91b8-3876adf4330f)
