### ISSUE TITLE
Polkadot Vault ethereum accounts support

### ISSUE THREAD

**Issue by 0xKheops** [TalismanSociety/talisman#918]
PV seems to be compatible with moonbeam/moonriver, but Talisman sees QR code as invalid

**Comment by alecdwm** [comment]
The `invalid qr code` error has been fixed, but we still can't sign Moonbeam txs with PV.

However, it also doesn't seem to work when using PV with PJS apps:

1. Add Moonbeam chainspec & metadata to PV via https://metadata.novasama.io
2. Create Moonbeam account in PV
3. Connect Moonbeam account to https://polkadot.js.org/apps/
4. Prepare a transfer TX to be signed by the PV account
5. Scan the QR code with the vault, and note the `Please Add The Network You Want To Transact in` error

<div align="center">
<img src="https://github.com/user-attachments/assets/7b9dd75b-a1f8-4e8e-8bf8-567998bfd7c5" width="33%" />
</div>

**Comment by chidg** [comment]
Closed by #1535
