### ISSUE TITLE
Talisman stuck on "Analysing Transaction" when signing TX from Polkadot dev node 

### ISSUE THREAD

**Issue by jsdw** [TalismanSociety/talisman#923]
When I attempt to sign a transaction using Talisman via a local Polkadot `--dev` node, it gets stuck on an "Analysing transaction, this shouldn't take long" screen and does not progress.

I'd like to try using Talisman against a local dev node in order to check that I can manually construct and sign extrinsics using it (specifically to work out how to construct and send the appropriate payload to the extension, ideally without using Polkadot.js).

**To Reproduce**

1. Install Polkadot, eg:
   ```
   git clone https://github.com/paritytech/polkadot.git
   cd polkadot
   cargo install --path .
   ```
    (Expects Rust/cargo to be installed)
1. Start a local polkadot dev node: `polkadot --dev`
1. With the Talisman extension enabled, open https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/extrinsics and attempt to submit some transaction using a Talisman account (I loaded the dev `Alice` account into Talisman to do this).

**Expected behavior**

The transaction should be signed by Talisman.

**Screenshots**

Instead, I see this indefinitely:

<img width="399" alt="Screenshot 2023-07-10 at 14 53 05" src="https://github.com/thoughtworks/talisman/assets/3799193/cf724ce6-ead1-4088-ad4b-a404c89f75d2">

**Version Information**

 - MacOS 11.6.8
 - Firefox 114.0.2
 - Talisman Extension 1.17.4
 - Polkadot 0.9.43-d5616884690 (the latest as of this issue; I also tried an older version to no avail)

**Comment by chidg** [comment]
Thanks for the report @jsdw

**Comment by Sotatek-TungLe2** [comment]
I'm facing this issue too. Since last Friday.

**Comment by chidg** [comment]
> I'm facing this issue too. Since last Friday.

Hi @Sotatek-TungLe2, did it work for you from before Friday?
If so you may be able to make a local build of [v1.17.3](https://github.com/TalismanSociety/talisman/releases/tag/v1.17.3) and see if that solves the problem.

**Comment by Sotatek-TungLe2** [comment]
> > I'm facing this issue too. Since last Friday.
> 
> Hi @Sotatek-TungLe2, did it work for you from before Friday? If so you may be able to make a local build of [v1.17.3](https://github.com/TalismanSociety/talisman/releases/tag/v1.17.3) and see if that solves the problem.

Yes. Before Friday, I still can transfer tokens.

**Comment by Sotatek-TungLe2** [comment]
![image](https://github.com/TalismanSociety/talisman/assets/99628322/0940d5d2-ae79-4b51-88f8-8d60dee38d46)
How can I role back on local v.1.17.3 ?
