### ISSUE TITLE
Manage Accounts improvements

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#932]
### Code review improvements
- [x] Unit tests on `store.catalog.ts`
- [x] Attempt to reduce `find`s inside loops in the store
- [x] Refactor store to remove static methods shared with UI

### Usability & Sentinels feedback improvements
- [x] Redo account actions dropdown 
  - [x] Move to sidebar (https://github.com/TalismanSociety/talisman/issues/811)
  - [x] Add 'Manage accounts` as first option, even when no account selected
  - [x] Remove `Add custom token` option
- [x] Fix folder open/close UX
  - [x] Always show chevron & three dots menu
  - [x] Show empty dropzone for empty folders
- [x] Investigate Ramo's bug with account balances in folder

**Comment by prury** [comment]
>     * [x]  Investigate Ramo's bug with account balances in folder

❤️
