### ISSUE TITLE
Resolve On-Chain Identity

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#960]

**Comment by 0byt** [comment]
- [x] Support ENS + Polkadot Identity System (native)
- [x] Sending funds (resolve address underneath) 
- [x] Address book (resolve address in list, not replace contact name)
~~- [ ] InTransaction history (resolve address in list)~~ (edit: @chidg)
- [x] Main accounts page (resolve address additionally, especially for watched account)
- [x] Consider autofill of the ENS name when address is being added to the address book and/or watched account

**Comment by alecdwm** [comment]
https://github.com/TalismanSociety/talisman/pull/1006

**Comment by chidg** [comment]
Closed as complete
