### ISSUE TITLE
[Bug] Substrate transaction fee estimate loads very slow 

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#970]
**Describe the bug**
TX fee estimate on substrate loads very slowly. 

**To Reproduce**
Initiate a tx (i.e. staking)
See tx fee estimate

**Expected behaviour**
Currently takes many secs, expect it to be <1s.

**Screenshots**
<img width="384" alt="image" src="https://github.com/TalismanSociety/talisman/assets/119995565/c647604d-70e6-400d-9f0b-d8d21c689532">

**Environment (please complete the following information):**

- OS: Mac
- Browser: Brave
- Version: 1.18.0

**Comment by 0xKheops** [comment]
good catch there !
