### ISSUE TITLE
Show address for address book contact in send funds dialog

### ISSUE THREAD

**Issue by chidg** [TalismanSociety/talisman#982]
Currently when selecting an address book contact from the recipients list in the send funds UI, the contact name is displayed but not the address. This can lead to a situation where if a user has multiple contacts with the same or similar names, they could select the wrong one.

We can make this more clear by showing the address in two places:
1. In the recipients list, on a second line underneath the name of the contact
![Screenshot 2023-08-02 at 10 06 19 am](https://github.com/TalismanSociety/talisman/assets/3326734/5f77d410-c14b-455d-9447-cd6cccd6d755)

2. In the Amount entry screen, as a tooltip on the recipient component
![Screenshot 2023-08-02 at 10 06 28 am](https://github.com/TalismanSociety/talisman/assets/3326734/093f62ea-1b7d-47f1-8663-592919ca7f14)

To be completed in conjunction with #960

**Comment by chidg** [comment]
@alecdwm could you confirm that this has been done in #960 ?

**Comment by alecdwm** [comment]
@chidg it has!
