### ISSUE TITLE
Get Chaindata off  Squid to Cloudflare

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#984]

**Comment by alecdwm** [comment]
Duplicate of https://github.com/TalismanSociety/talisman/issues/1076

**Comment by 0xKheops** [comment]
@alecdwm should we yeet this issue ?

**Comment by alecdwm** [comment]
@0xKheops yeah! Closing as duplicate (of https://github.com/TalismanSociety/talisman/issues/1076)
